version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo-producer-consumer
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  kafka-1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CONTROLLER://kafka-1:9093,CLIENT://kafka-1:29092,EXTERNAL://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-1:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_KRAFT_CLUSTER_ID=fztU8TfA55Holo3Cd0V3
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=yes
    volumes:
      - kafka-1_data:/bitnami/kafka
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --bootstrap-server localhost:8082 --list",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

#  producer:
#    # build: ./producer
#    image: nagendra9/iot-platform-producer:0.1
#    container_name: producer
#    environment:
#      - JWT_SECRET=${JWT_SECRET}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongo
#      - kafka-1
#    networks:
#      - app-network
#
#  consumer:
#    # build: ./consumer
#    image: nagendra9/iot-platform-consumer:0.1
#    container_name: consumer
#    ports:
#      - "8082:8082"
#    depends_on:
#      - mongo
#      - kafka-1
#      - producer
#    networks:
#      - app-network

volumes:
  mongo_data:
    driver: local
  kafka-1_data:
    driver: local

networks:
  app-network:
    driver: bridge
