version: '3.8'
# hello
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network

  kafka-1:
    image: bitnami/kafka:latest
    ports:
      - "8082:8082"
    environment:
      - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:8083
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CONTROLLER://kafka-1:8083,CLIENT://kafka-1:29092,EXTERNAL://0.0.0.0:8082
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-1:29092,EXTERNAL://localhost:8082
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_KRAFT_CLUSTER_ID=fztU8TfA55Holo3Cd0V3
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=yes
    volumes:
      - kafka-1_data:/bitnami/kafka
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --bootstrap-server localhost:8082 --list"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - kafka-network

volumes:
  mongo_data:
    driver: local
  kafka-1_data:
    driver: local

networks:
  mongo_network:
    driver: bridge
  kafka-network:
    driver: bridge