#spring.application.name=iot-platform
spring:
  application:
    name: iot-platform
  data:
    mongodb:
      host: localhost
      port: 27017
      database: iot-platform
jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org:
      springframework:
        security=DEBUG: